{
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "cve@gitlab.com",
            "ID": "CVE-2021-22239",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "GitLab",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": ">=14.1, <14.1.2"
                                            },
                                            {
                                                "version_value": ">=14.0, <14.0.7"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "GitLab"
                    }
                ]
            }
        },
        "credit": [
            {
                "lang": "eng",
                "value": "This vulnerability has been discovered internally by the GitLab team"
            }
        ],
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "An unauthorized user was able to insert metadata when creating new issue on GitLab CE/EE 14.0 and later."
                }
            ]
        },
        "impact": {
            "cvss": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "NONE",
                "baseScore": 4.9,
                "baseSeverity": "MEDIUM",
                "confidentialityImpact": "NONE",
                "integrityImpact": "LOW",
                "privilegesRequired": "LOW",
                "scope": "CHANGED",
                "userInteraction": "NONE",
                "vectorString": "AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:L/A:N",
                "version": "3.1"
            }
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "Improper authentication in GitLab"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://gitlab.com/gitlab-org/gitlab/-/issues/336301",
                    "refsource": "MISC",
                    "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/336301"
                },
                {
                    "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22239.json",
                    "refsource": "CONFIRM",
                    "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22239.json"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "cve@gitlab.com",
                "ID": "CVE-2021-22239"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "An unauthorized user was able to insert metadata when creating new issue on GitLab CE/EE 14.0 and later."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://gitlab.com/gitlab-org/gitlab/-/issues/336301",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/336301"
                    },
                    {
                        "name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22239.json",
                        "refsource": "CONFIRM",
                        "tags": [],
                        "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22239.json"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-09-09T15:50Z",
        "publishedDate": "2021-09-09T15:15Z"
    }
}